image: google/cloud-sdk:latest

pipelines:
  default:
    - step:
        name: Deploy to GKE
        script:
          # Step 1: Authenticate with Google Cloud
          - echo $GCP_SERVICE_ACCOUNT_KEY > /tmp/key.json
          - gcloud auth activate-service-account --key-file /tmp/key.json
          - gcloud config set project testproject-00717777
          - gcloud config set compute/zone us-central1-c

          # Step 2: Get GKE Cluster Credentials
          - gcloud container clusters get-credentials demo-cluster

          # Step 3: Use Kustomize to Apply the Kubernetes Configuration
          - kubectl apply -k .


