apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: newapps.apps.test.dev           
spec:
  group: apps.test.dev                  
  names:
    kind: NewApp                        
    listKind: NewAppList                
    plural: newapps                     
    singular: newapp                    # Singular name
  scope: Namespaced                    
  versions:
    - name: v1                         
      served: true                      
      storage: true                     
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
      subresources:
        status: {}                      
